on: [push]

jobs:
  test1:
    runs-on: ubuntu-latest
    name: basic test

    strategy:
      fail-fast: false
      matrix:
        check:
          - '{"dog" : "dog", "cat": "cat"}'
          - '{ "(dog|cat)" : "animal"   }'
          - '{ "(dog|cat)" : "animal", "(volvo|BMW)" : "Car"}'
          - '{ "(volvo|BMW)" : "Car", "(dog|cat)" : "animal"}'
    steps:
      - uses: actions/checkout@v2
      - name: Manual Action Test
        id: test_action
        uses: ./
        with:
          input: "this string has animals: cat\n and cars: Volvo "
          json_match: ${{ matrix.check }}
          fail_if_no_match: True
      - run: |
          echo "${{ steps.test_action.outputs.result }}"

  test2:
    runs-on: ubuntu-latest
    name: escapeTests

    strategy:
      fail-fast: false
      matrix:
        check:
          - '{
          "(?i)animal[^\\w\\n\\r]*dog\\b" : "dog", 
          "(?i)animal[^\\w\\n\\r]*cat\\b": "cat"
          }'
    steps:
      - uses: actions/checkout@v2
      - name: Manual Action Test
        id: test_action
        uses: ./
        with:
          input: "animal:   CAT"
          json_match: ${{ matrix.check }}
          fail_if_no_match: True
      - run: |
          echo "${{ steps.test_action.outputs.result }}"
