on: [push]

jobs:
  test1:
    runs-on: ubuntu-latest
    name: test

    strategy:
      matrix:
        check:
          - '{"dog" : "dog", "cat": "cat"}'
          - '{ "animal" : "(dog|cat)"  }'
          - '{ "/" : "/(dog|cat)/im", "Car" : "/(volvo|BMW)/im"}'
          - '{ "Car" : "(volvo|BMW)", "animal" : "(dog|cat)" }'
    steps:
      - uses: actions/checkout@v2
      - name: Manual Action Test
        id: test_action
        uses: ./
        with:
          input: "this string has animals: horse\n and cars: Volvo "
          json_match: ${{ matrix.check }}
      - name: Show result
        run: |
          echo "${{ steps.test_action.outputs.result }}"

  test2:
    runs-on: ubuntu-latest
    name: test

    strategy:
      matrix:
        check:
          - '{
          "\/animal[^\\w\\n\\r]*dog\\b\/i" : "dog", 
          "\/animal[^\\w\\n\\r]*cat\\b\/i": "cat"
          }'
    steps:
      - uses: actions/checkout@v2
      - name: Manual Action Test
        id: test_action
        uses: ./
        with:
          input: "animal:   CAT"
          json_match: ${{ matrix.check }}
          success_if_no_match: false
      - name: Show result
        run: |
          echo "${{ steps.test_action.outputs.result }}"
